"""add_name_to_assets

Revision ID: 0c1a330b4c30
Revises: a42cef442926
Create Date: 2026-06-02 14:01:12.588853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a330b4c30'
down_revision: Union[str, None] = 'a42cef442926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
