"""add_name_to_assets

Revision ID: a42cef442926
Revises: 3157c58f0353
Create Date: 2026-06-02 13:55:39.303923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a42cef442926'
down_revision: Union[str, None] = '3157c58f0353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', 'SENT', 'FAILED', name='alertstatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::alertstatus"))
    op.add_column('assets', sa.Column('name', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('logo_url', sa.String(), nullable=True))
    op.drop_column('assets', 'current_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('assets', 'logo_url')
    op.drop_column('assets', 'is_active')
    op.drop_column('assets', 'exchange')
    op.drop_column('assets', 'industry')
    op.drop_column('assets', 'sector')
    op.drop_column('assets', 'name')
    op.alter_column('alerts', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'PENDING', 'SENT', 'FAILED', name='alertstatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::alertstatus"))
    # ### end Alembic commands ###
